### ISSUE TITLE
Override inventory click event

### ISSUE THREAD

**Issue by Lemar98** [Rysefoxx/RyseInventory#10]
I want to make it so that the player can put into inventory / pick up from inventory items . How can this be done?

**Comment by Rysefoxx** [comment]
You can use the #ignoreClickEvent method in the Inventory Builder and use DisabledInventoryClick.TOP. Now you can add or remove items everywhere except for the items you placed with IntelligentItem#empty or IntelligentItem#of. Alternatively you can place an item in the inventory with IntelligentItem#ignored. If you use IntelligentItem#ignored you don't need DisabledInventoryClick.TOP, because then this item can be placed out and in again by the user.

**Comment by Rysefoxx** [comment]
In the upcoming update there will be the possibility to use #ignoredSlots in the builder. This method will then allow users to add or remove items in these slots that you have defined.

**Comment by Lemar98** [comment]
Thanks
I will try it later and give you feedback

**Comment by Lemar98** [comment]
I now place items in inventory as IntelligentItem#ignored. This works great for me, but there is a small problem: the player cannot put an item into inventory using shift. Can this be resolved somehow?

**Comment by Rysefoxx** [comment]
Not directly. I could make the inventory more flexible, so you can set something like that yourself.

**Comment by Lemar98** [comment]
I would be very grateful to you for such functionality

**Comment by Lemar98** [comment]
I would be very grateful to you for such functionality

**Comment by Lemar98** [comment]
one more question: is there any way to get content from all inventory pages? I need to check if the inventory has changed when closing the inventory and save the changes

**Comment by Rysefoxx** [comment]
Both will be available in the upcoming update. (As a beta, I have tested a lot, but may still have bugs).

**Comment by Rysefoxx** [comment]
[Update v1.4.6 is out](https://github.com/Rysefoxx/RyseInventory/releases/tag/v1.4.6)

**Comment by Lemar98** [comment]
1. Method #enableAction(Action.DOUBLE_CLICK, Action.MOVE_TO_OTHER_INVENTORY) still doesn't allow to put items into inventory via shift (maybe it shouldn't allow it, but this method doesn't allow me anything else)

2. You can use the #getAllData() method only from InventoryContents, but I need to receive all items when the inventory is closed, for example, through the #listener(new EventCreator<>(InventoryCloseEvent.class, event -> )) method, how can I get InventoryContents from here?

**Comment by Rysefoxx** [comment]
1) For me, Action.MOVE_TO_OTHER_INVENTORY. Maybe you can show single code cuts. It is possible that an error has crept in there.

Alternatively describe how I reprod the error.

2)You can get the InventoryContents from a player via the InventoryManager.

**Comment by Lemar98** [comment]
1. https://pastebin.com/vK6fQJwF
This code is not allow me to put items from custom inventory to player inventory by SHIFT click

2. https://pastebin.com/u3AZ8K2e
This code return me false

**Comment by Rysefoxx** [comment]
1) This is because items can only be shifted in where you have specified. With #enableAction you only say that it is possible to put in the items with Shiftclick.

Try to use #ignoredSlots to select the slots where you can remove / add items. The result is that the items can also be shifted in there.

2) This is because I delete the data before your custom event. In the next update the data will be deleted only after your InventoryCloseEvent, so it should not output false anymore.

Please update the version to 1.4.7

**Comment by Lemar98** [comment]
1. https://pastebin.com/mL53w1rS
I use this code and still can't put items in ryse inventory using shift :(

2. Everything works, thanks!

**Comment by Rysefoxx** [comment]
![Minecraft-1 8 8-29-August-2022](https://user-images.githubusercontent.com/59345967/187210684-d3a98a2c-2791-4348-af00-9463a39ba8e2.gif)
![image](https://user-images.githubusercontent.com/59345967/187210755-941f67a6-82ef-486d-a394-1a8bec8873a5.png)

I don't know exactly what you are trying to do. I used your #ignoredSlots method and reduced the area. As you can see I can shift all items in the range 0-8 or add them by drag and drop.

**Comment by Lemar98** [comment]
Sorry, this is my mistake. For testing, I disabled the #.enableAction(Action.MOVE_TO_OTHER_INVENTORY) function and forgot to enable it back, so I couldn't put items in inventory.

However, now there is a new problem. If the inventory is full and the player tries to shift an item from their inventory to the ryse inventory by pressing SHIFT, the first item in slot 0 in the ryse inventory will be replaced by the one the player is trying to put in. Is there any way to control this?

**Comment by Rysefoxx** [comment]
Yes I have already found & fixed this error. Will be fixed in the next update.

**Comment by Lemar98** [comment]
I'll be waiting, thanks!

**Comment by Rysefoxx** [comment]
Since it is an already critical bug, I will start the update now. Check every now and then if update 1.4.8 is already available.

**Comment by Lemar98** [comment]
I noticed another problem. Items that the player himself put into the inventory for some reason are not returned via InventoryContents#getAllData()

**Comment by Rysefoxx** [comment]
> I noticed another problem. Items that the player himself put into the inventory for some reason are not returned via InventoryContents#getAllData()

This is most likely because you are calling the #isIgnoreManualItems method. This will only add them to the inventory, but never store them in the "head".

**Comment by Lemar98** [comment]
Indeed it worked for me. Something I'm too stupid today ... Thank you, buddy!
