### ISSUE TITLE
Each page should have its own rows count

### ISSUE THREAD

**Issue by Lemar98** [Rysefoxx/RyseInventory#11]
Is it possible to make it so that each new page can have a setting about how many rows it should have? I think it would make your plugin more flexible

**Comment by Rysefoxx** [comment]
No the function does not exist. I think the idea is not bad and will implement it soon.

**Comment by Rysefoxx** [comment]
Oh, is that what you mean?
The player has e.g. unlocked 1 row at the beginning and if he improves his "skills", he can unlock e.g. the 2 row in the inventory?

You could then simply let the player open the new inventory with the new row?

I had something like this in my head now:
You can select the size for individual pages. E.g. 1 side there are only 3 rows, if he changes to the 2 side there are e.g. 4 rows.

**Comment by Lemar98** [comment]
The problem with the option you suggested is that in this case it will be problematic to make pagination. For example, a player has 19 rows open - that's 3 pages and 1 row. When switching to a new page where there should be 1 row, I will not be able to transfer pagination.

What you imagined in your head should fit my tasks.

**Comment by Rysefoxx** [comment]
Of course, my idea does not work for pagination. Nevertheless, it can be useful outside of pagination.

**Comment by Lemar98** [comment]
Can you somehow combine your idea with saving pagination?

**Comment by Rysefoxx** [comment]
I don't see how that can be done. If I tell the SlotIterator to start from row 1 and column 1 to row 4 and column 7, but there is no row 4 on the next page, how should the pagination work? 

I could say, just fill the slots as before, but if there is no row 4 on this page as on the previous page, just stop.

**Comment by Lemar98** [comment]
Good
Do you implement your idea in order to set your own rows for each page?

**Comment by Rysefoxx** [comment]
Yes

**Comment by Rysefoxx** [comment]
Sorry that it takes a little longer. Meanwhile I have to work again, this Friday/Saturday the update should come.

**Comment by Lemar98** [comment]
It's okay, I can wait. Thanks for your hard work!

**Comment by Rysefoxx** [comment]
[Update v1.4.9](https://github.com/Rysefoxx/RyseInventory/releases/tag/v1.4.9) If there are any problems, of course report them.
