### ISSUE TITLE
Right click menu NPE

### ISSUE THREAD

**Issue by Lemar98** [Rysefoxx/RyseInventory#12]
When player click to ryse inventory for an empty slot, plugin throw null pointer exception
https://pastebin.com/jq7KAPCZ

**Comment by Rysefoxx** [comment]
Fixed in the upcoming update.

**Comment by Rysefoxx** [comment]
[Update v1.4.9](https://github.com/Rysefoxx/RyseInventory/releases/tag/v1.4.9) If there are any problems, of course report them.
