### ISSUE TITLE
Add stop function for IntelligentMaterialAnimator

### ISSUE THREAD

**Issue by tuanzisama** [Rysefoxx/RyseInventory#13]
In cases, the animator will be set `loop`. but it cannot stop to set another `ItemStack`.

Can the [IntelligentMaterialAnimator](https://github.com/Rysefoxx/RyseInventory/blob/master/plugin/src/main/java/io/github/rysefoxx/pagination/IntelligentMaterialAnimator.java) class be provided with a way to stop the animation? or make [getTask](https://github.com/Rysefoxx/RyseInventory/blob/master/plugin/src/main/java/io/github/rysefoxx/pagination/IntelligentMaterialAnimator.java#L147) from protected to public?

make `getTask` from protected to public just suggestion, I'm not sure it stable.
```java
materialAnimator.getTask().cancel();
```

**Comment by tuanzisama** [comment]
Currently, I use the `Reflection` to get `task` property.

```java
Class animatorClass = materialAnimator.getClass();
Field taskField = ReflectUtil.getField(animatorClass, "task");
taskField.setAccessible(true);
Object taskObj = taskField.get(materialAnimator);
if (taskObj instanceof BukkitTask) {
    BukkitTask task = (BukkitTask) taskObj;
    task.cancel();
}
```

**Comment by Rysefoxx** [comment]
Coming in the next update.

**Comment by Rysefoxx** [comment]
[Update v1.4.9](https://github.com/Rysefoxx/RyseInventory/releases/tag/v1.4.9) If there are any problems, of course report them.
