### ISSUE TITLE
Condition for function apply

### ISSUE THREAD

**Issue by Lemar98** [Rysefoxx/RyseInventory#14]
I want to make sure that the player can't pick up items from the ryse inventory without some permission.

Since the inventory is built with the ignore slots function, I can't control the player clicking on those slots.

Can I somehow implement my idea?

I can suggest adding a specific condition for applying the function in the builder. For example https://pastebin.com/fMsnyfHb

**Comment by Rysefoxx** [comment]
Function will be available in the next update.

**Comment by Rysefoxx** [comment]
[Update v1.4.9](https://github.com/Rysefoxx/RyseInventory/releases/tag/v1.4.9) If there are any problems, of course report them.
