### ISSUE TITLE
[Dependency] ItemBuilder

### ISSUE THREAD

**Issue by fnrcum** [Rysefoxx/RyseInventory#15]
Is the `ItemBuilder` from the examples 
![image](https://user-images.githubusercontent.com/10963542/190099083-96027215-cd25-4ea2-a425-3c0137132c85.png)

this plugin as a dependency? https://www.spigotmc.org/resources/api-itembuilder.12502/

**Comment by fnrcum** [comment]
Just to add some info, I'm asking as this is how it is in the examples and I am unsure if the examples are outdated

**Comment by Rysefoxx** [comment]
![image](https://user-images.githubusercontent.com/59345967/190458973-f96e44b6-fca5-4219-b8f0-242e1755649c.png)

It is simply an ItemBuilder that I have created. You can use your ItemBuilder for it just the same.
