### ISSUE TITLE
Err "There is no page with the number 2"

### ISSUE THREAD

**Issue by Lemar98** [Rysefoxx/RyseInventory#16]
This code throw error for me: https://pastebin.com/Qee8Ai2v

Error: https://pastebin.com/eAQKwGjS

When I call "page.isLast()" it prints "false" and when I call "page.lastPage()" it prints "2". Does this mean that the second page still exists?

Why might this be happening?

**Comment by Rysefoxx** [comment]
Looks like you are using the #rows(Page) method. The error is because you didn't enter anything for this page in #rows(Page) and it can't find this page.

Could I see your builder?

**Comment by Lemar98** [comment]
https://pastebin.com/2ddqUiS8

**Comment by Rysefoxx** [comment]
I can hardly do anything with that. You have your page array, what values are in there?

Have you possibly already debugged?

**Comment by Lemar98** [comment]
https://pastebin.com/qtMV5ASJ

**Comment by Rysefoxx** [comment]
You have page 1 (0) and page 2 (1). Somehow you are trying to access page 3 (2), which does not exist.

**Comment by Lemar98** [comment]
Are you saying that the problem is in my algorithm for creating an array of pages?

**Comment by Rysefoxx** [comment]
![image](https://user-images.githubusercontent.com/59345967/190903305-412c92f3-f0d6-4025-9657-119002b8bcb8.png)
No in the nextSlotAlgorithm() method I call the size() method. When it finds no more slot on the page, it increases the page. It seems that it then goes to the next page where it then gets the error because it doesn't exist.

**Comment by Lemar98** [comment]
Interesting

**Comment by Lemar98** [comment]
What do you say? Are there any successes?

**Comment by Rysefoxx** [comment]
Unfortunately, I have only now found the time to fix the error.

**Comment by Rysefoxx** [comment]
[Update v1.5.0](https://github.com/Rysefoxx/RyseInventory/releases/tag/v1.5.0) If there are any problems, of course report them.
