### ISSUE TITLE
Algorithm does not work perfectly with SlotIterator#endPosition

### ISSUE THREAD

**Issue by Rysefoxx** [Rysefoxx/RyseInventory#24]
**Describe the bug**
The items are placed incorrectly.

**Additional context**
Already fixed. Available in update 1.5.1

**Comment by Baakarshan** [comment]
Really sorry for the help-seeking comment I posted on spigotmc.org website. Awkwardly to say, I was using this site for the first time to find an API, and I'm a creator who has just started developing Bukkit plugins. I sincerely thank you for providing an API that allows me to take fewer times when creating plugins.

**Comment by Rysefoxx** [comment]
[Changelog v1.5.1](https://github.com/Rysefoxx/RyseInventory/releases/tag/v1.5.1). If errors occur please create a new TIcket.
