### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 54

### ISSUE THREAD

**Issue by Lemar98** [Rysefoxx/RyseInventory#25]
**Describe the bug**
With the new version 1.5.1, I can't run my previous plugin at all. O_o
Every time I try to open the inventory the server shows me an error in the header.

**Error**
https://pastebin.com/fMMMK18v

**To Reproduce**
1. run my code in your localhost

**Expected behavior**
I want the inventory to open.

**Code (Optional)**
https://pastebin.com/VRA4rsCr

**Comment by Rysefoxx** [comment]
As already mentioned, you can:
int size = pagination.inventory().size(contents);
not so easily. As already explained in the previous post.
Furthermore, I can't try your code and see what the problem is, because you use some classes there that I don't have.

I'll still try to reproduce your problem as good as possible.

**Comment by Lemar98** [comment]
I already answered earlier that I can't help but get the size of the current page, as it is necessary for further logic. Perhaps I need some alternative?

As for your suggestions that you can't run my code on your own, that's not true. You don't need my custom inventory classes at all. Instead, you must specify the values ​​yourself. I did it for you without my custom clasess in this code: https://pastebin.com/xwv5cnDL
Please try it.

**Comment by Rysefoxx** [comment]
Fun fact, you have not defined your start slot in the SlotIterator. Thus the start slot is -1 and thus the error comes. Maybe I should describe the error better or throw an error.

**Comment by Lemar98** [comment]
it's really works for me, lol
thanks

**Comment by Rysefoxx** [comment]
> it's really works for me, lol thanks

Glad to hear👍
