### ISSUE TITLE
[Improvements] Addition open method for data

### ISSUE THREAD

**Issue by DotDebian** [Rysefoxx/RyseInventory#3]
Can you consider going from `@Nullable String[] keys, @Nullable Object[] values` to `@Nullable Map<String, Object> data` ?

It could be way more better for readability

**Comment by Rysefoxx** [comment]
Hey, thanks for the suggestion.

In the upcoming update 1.3.1 there will be the open method, also for Map<String, Object>

Yes you are right, I have revised the RyseInventory#transferData method. Thank you for the improvements.

**Comment by Rysefoxx** [comment]
Update 1.3.1 includes the new content.

[Changelog](https://github.com/Rysefoxx/RyseInventory/releases/tag/v1.3.1)
