### ISSUE TITLE
InventoryClickEvent doesn't want cancel

### ISSUE THREAD

**Issue by Lemar98** [Rysefoxx/RyseInventory#31]
**Describe the bug**
I need to prevent players from putting some items in their inventory. For a test, I'm trying to prevent them from putting materials into GLASS and GRASS inventory.

There was a problem with canceling an event if its action is "MOVE_TO_OTHER_INVENTORY". The event is simply not cancelled.

I tried exactly the same code with normal listener from BukkitAPI and simple chest, there my code works fine

**To Reproduce**
1. Create any inventory and allow items to be placed there
2. Give the inventory builder my event listener
3. Start the server and try putting forbidden items (GLASS and GRASS) in your inventory using shift

**Expected behavior**
The event should be canceled if the player tries to put a prohibited item in inventory using shift

**Code (Optional)**
https://pastebin.com/yPUavgBU

**Comment by Rysefoxx** [comment]
In 1.5.2, the main InventoryClick event in my library is now canceled when the custom event is canceled.
