### ISSUE TITLE
InventoryClickEvent doesn't want cancel again

### ISSUE THREAD

**Issue by Lemar98** [Rysefoxx/RyseInventory#32]
**Describe the bug**
I need to prevent players from putting some items in their inventory. For a test, I'm trying to prevent them from putting materials into GLASS and GRASS inventory.

There was a problem with canceling an event if its action is "PLACE_SOME" or "PLACE_ONE" or "PLACE_ALL". The event is simply not cancelled.

I tried exactly the same code with normal listener from BukkitAPI and simple chest, there my code works fine

**To Reproduce**

Create any inventory and allow items to be placed there
Give the inventory builder my event listener
Start the server and try putting forbidden items (GLASS and GRASS) in your inventory using mouse cursor
Expected behavior
The event should be canceled if the player tries to put a prohibited item in inventory

**Code (Optional)**
https://pastebin.com/EpuK44E2

**Comment by Rysefoxx** [comment]
Everything works as it should. The event is canceled, you most likely used #ignoredSlots and specified the slot. Then you can still place the item.

**Comment by Lemar98** [comment]
Yes you are right, sorry
