### ISSUE TITLE
Debug prints when init() is called

### ISSUE THREAD

**Issue by Lemar98** [Rysefoxx/RyseInventory#33]
**Describe the bug**
Every time the init() method is called, a number is written to the console. As I noticed, this appeared after updating to 1.5.2. Most likely you forgot to remove some debugging information, since I have no places in the plugin where I could output something to the console.

**To Reproduce**
1. run init() method

**Screenshots**
![image](https://user-images.githubusercontent.com/45980309/196029699-bfe242b3-ab0a-4b29-9450-d398852ba395.png)

**Comment by Rysefoxx** [comment]
Yep :) My fault. Already removed

**Comment by Rysefoxx** [comment]
[Update v1.5.3](https://github.com/Rysefoxx/RyseInventory/releases/tag/v1.5.3)

Attention! The GroupId has changed. Please report errors.
