### ISSUE TITLE
Two identical custom listeners don't work together

### ISSUE THREAD

**Issue by Lemar98** [Rysefoxx/RyseInventory#36]
**Describe the bug**
When working with custom listeners, I found that two identical ones (for example, InventoryClickEvent) will not work together, but only the one that was added first.

Question: Is this how it's meant to be?

If so, then my suggestion for improving the API is to allow developers to implement multiple listeners and arrange it as a queue

**Comment by Rysefoxx** [comment]
> **Describe the bug** When working with custom listeners, I found that two identical ones (for example, InventoryClickEvent) will not work together, but only the one that was added first.
> 
> Question: Is this how it's meant to be?
> 
> If so, then my suggestion for improving the API is to allow developers to implement multiple listeners and arrange it as a queue

Of course, identical events are overwritten. Why cache 2 exactly identical events when 1 is enough?

**Comment by Lemar98** [comment]
For some inventories, I need to modify the default InventoryClick listener, so I thought about it

**Comment by Rysefoxx** [comment]
You will not be able to override my InventoryClickEvent.
