### ISSUE TITLE
Getting an error while opening gui

### ISSUE THREAD

**Issue by Wupin** [Rysefoxx/RyseInventory#37]
**Describe the bug**
Every time i try to open menu i get this error https://pastebin.com/AMJfe6Ct

**To Reproduce**
Simply try to open menu with builder#open(player). My builder looks like this https://pastebin.com/nTGxhreH
LibraryPlugin#getInvManager() will just get a InventoryManager

**Comment by Wupin** [comment]
i just update to the lastest version (1.5.2) and remove manager from the build and now im getting this error https://pastebin.com/xBKEZ46B
Whole class: https://pastebin.com/qEYk4QPx

**Comment by Rysefoxx** [comment]
> i just update to the lastest version (1.5.2) and remove manager from the build and now im getting this error https://pastebin.com/xBKEZ46B Whole class: https://pastebin.com/qEYk4QPx

[17:08:27 ERROR]: [wLib] [ACF] Caused by: java.lang.IllegalStateException: No manager could be found. Please create an InventoryManager field in your main class.

Can you show your main class please?

**Comment by Wupin** [comment]
My fault for not reading the entire error. I think there's something missing in the main class. Unfortunately, I'm not home, so I can't check it right now.

**Comment by Wupin** [comment]
The fault was on my side because I did pass a main class in Builder#build which did not have an initialized InventoryManager.

**Comment by Rysefoxx** [comment]
@Wupin Glad to hear everything worked out :)
