### ISSUE TITLE
method InventoryContents#updateLore doesn't working

### ISSUE THREAD

**Issue by Lemar98** [Rysefoxx/RyseInventory#44]
**Describe the bug**
I am using the following code: https://pastebin.com/Kj65ME8Q
But the lore of the item is not updated even though the method returns true. Maybe I'm doing something wrong?

**To Reproduce**
1. Go to run my code

**Expected behavior**
The lore must be updated in opened inventory

api ver 1.5.3

**Comment by Rysefoxx** [comment]
Ich habe es schnell mal getestet. Bei mir geht es ohne Probleme. Hast du schon gedebugged?
[Code](https://hastebin-plus.herokuapp.com/3W3k4f7nin)

https://user-images.githubusercontent.com/59345967/201481173-7c254954-c1d8-4a4e-8109-eb0a15cad6f9.mp4

**Comment by Lemar98** [comment]
I sort of figured out what was going on, it was my bad code again...

I have one more question, is it possible to set the #update method execution time, let's say, to run not every tick, but every 5 seconds?

**Comment by Lemar98** [comment]
I find a #period method of builder in documentation, thanks for your answer!
