### ISSUE TITLE
Open GUI

### ISSUE THREAD

**Issue by jurian112211** [Rysefoxx/RyseInventory#5]
Hey there,

I looked through the wiki and examples and this looks like a very good library for gui menu's😀
I'm wanting to use this in my projects, but I didn't found a method to open it for the player yet.
How can I open a created inventory for a player?

Kind regards,
Jurian

**Comment by jurian112211** [comment]
Do I need to call the init method inside my GUI method with a player object to do it?

**Comment by jurian112211** [comment]
Also, why do I have to supply the InventoryContents object for the init method?
It's just set inside the method?

**Comment by Hassan7000** [comment]
When you build the ryseinventory object you just call open and provide the player.

**Comment by Rysefoxx** [comment]
As @Hassan7000 says, you need to use the #build method in the RyseInventory class.

**Comment by jurian112211** [comment]
Ah, so it's in the builder?
That was my first thought but I couldn't find it in the wiki xD

**Comment by Rysefoxx** [comment]
No the builder only used to set everything possible (RyseInventory.Builder)
With #build you build it to a RyseInventory where there is the method #open.

Yes in the wiki I didn't write down every little thing. Partly the more difficult to understand.

**Comment by jurian112211** [comment]
Awesome, I'll check it soon and let you know😀

**Comment by jurian112211** [comment]
What's the ItemBuilder?
`                        contents.set(0, IntelligentItem.empty(new ItemBuilder(Material.STONE).displayName("I am a stone with which nothing happens.").build()));`
My IDEA can't find the import.

**Comment by Rysefoxx** [comment]
A completely normal ItemBuilder. You would have to create it yourself or search for an existing one on Github.

Again for your information: Under examples there are not always complete solutions. It should only show how it can look like.

**Comment by jurian112211** [comment]
Okay, thank you!
Will close this now 👍
