### ISSUE TITLE
The NBTAPI Plugin gets shaded

### ISSUE THREAD

**Issue by tr7zw** [Rysefoxx/RyseInventory#6]
Hey there.
Your plugin uses the maven shade plugin, but didn't mark dependencies as provided, causing them to get shaded.
Currently, this results in the RyseInventory plugin overwriting parts of the NBTAPI plugin, potentially breaking both and anything depending on them entirely. This issue also extends to many compile-time annotations that get shaded into the final jar.
Either shade the API(with a relocation), or mark it as provided(in this case the plugin.yml is missing its declaration).
For more info: https://github.com/tr7zw/Item-NBT-API/wiki/Using-Maven

**Comment by Rysefoxx** [comment]
Hey.
Thanks for the message. Unfortunately I didn't notice it myself.
The API should now be shaded with a relocation in update 1.4.0.

This issue is not closed directly. If you still encounter errors, feel free to post them here. Otherwise I will close the issue on August 14.

**Comment by Rysefoxx** [comment]
Oh you mean

instead of this:

<dependency>
    <groupId>de.tr7zw</groupId>
    <artifactId>item-nbt-api-plugin</artifactId>
    <version>2.10.0</version>
</dependency>

I'll take that:

<dependency>
    <groupId>de.tr7zw</groupId>
    <artifactId>item-nbt-api</artifactId>
    <version>2.10.0</version>
</dependency>

Or am I possibly misunderstanding you right now?




Am Di., 16. Aug. 2022 um 17:02 Uhr schrieb tr7zw ***@***.***>:

**Comment by Rysefoxx** [comment]
Oh you mean

instead of this:

<dependency>
    <groupId>de.tr7zw</groupId>
    <artifactId>item-nbt-api-plugin</artifactId>
    <version>2.10.0</version>
</dependency>

I'll take that:

<dependency>
    <groupId>de.tr7zw</groupId>
    <artifactId>item-nbt-api</artifactId>
    <version>2.10.0</version>
</dependency>

Or am I possibly misunderstanding you right now?

Am Di., 16. Aug. 2022 um 17:02 Uhr schrieb tr7zw ***@***.***>:

**Comment by tr7zw** [comment]
Yea exactly. The ``-plugin`` dependency is the plugin itself, only used when having it as a normal dependency in the plugin.yml.
