### ISSUE TITLE
Get player input

### ISSUE THREAD

**Issue by NotZer0Two** [Rysefoxx/RyseInventory#8]
Hi a question im using this lib for a plugin, how i can make user just click and have a to type? Calling an event inside the gui or idk

**Comment by Rysefoxx** [comment]
I don't understand your question. In general, I don't understand the whole sentence.

Please revise your sentence again so that I can help you.

**Comment by NotZer0Two** [comment]
For example a user click in the stone block then the gui close and a title saying "input your message in chat" the user type in chat the sentence.

**Comment by Rysefoxx** [comment]
You can give the stone block an InventoryClickEvent and then close your title and inventory inside it (player.closeInventory())

**Comment by NotZer0Two** [comment]
Yes thats what i mean but i can call some even that runs only when the user clicks it?

**Comment by Rysefoxx** [comment]
I don't quite understand what you are trying to accomplish.

Do you want to do it like this?
You click on an item, it follows that the inventory closes and the player can make his input in the chat.

Once he has made his input, should the inventory open again?

**Comment by NotZer0Two** [comment]
found this https://www.spigotmc.org/threads/player-chat-inputs.437565/ works fine for who is wondering
